import re


PROJECT_TERM_ALIASES = {
    "Costing / GL Consequence": (
        "costing gl consequence",
        "costing / gl consequence",
        "costing and gl consequence",
    ),
    "Costing / GL Consequence Evidence": (
        "costing gl consequence evidence",
        "costing / gl consequence evidence",
        "costing and gl consequence evidence",
    ),
    "Costing": ("costing",),
    "GL consequence": ("gl consequence", "glconsequence"),
    "GL consequences": ("gl consequences", "glconsequences"),
    "financial consequence": ("financial consequence", "financialconsequence"),
    "financial consequences": ("financial consequences", "financialconsequences"),
    "provision reduction": ("provision reduction", "provisionreduction"),
    "out-of-pay": ("out of pay", "out-of-pay", "outofpay"),
    "remediation variance": ("remediation variance", "remediationvariance"),
    "RateSource / Rate Story": (
        "ratesource rate story",
        "ratesource / rate story",
        "rate source rate story",
        "rate source / rate story",
    ),
    "Rate Story": ("rate story", "ratestory"),
    "RateStory": ("ratestory", "rate story"),
    "RateSourceEvidenceIndex": ("ratesourceevidenceindex", "rate source evidence index"),
    "Rate Source Evidence Index": ("ratesourceevidenceindex", "rate source evidence index"),
    "pay guide rate evidence": ("pay guide rate evidence", "payguiderateevidence"),
    "rate amount": ("rate amount", "rateamount"),
    "selected rate": ("selected rate", "selectedrate"),
    "date-effective rate": ("date effective rate", "date-effective rate", "dateeffectiverate"),
    "award rate": ("award rate", "awardrate"),
    "account rate": ("account rate", "accountrate"),
    "class rate": ("class rate", "classrate"),
    "Decision Story": ("decision story", "decisionstory"),
    "DecisionStory": ("decisionstory", "decision story"),
    "DecisionEvidenceIndex": ("decisionevidenceindex", "decision evidence index"),
    "Decision Evidence Index": ("decisionevidenceindex", "decision evidence index"),
    "treatment selection": ("treatment selection", "treatmentselection"),
    "entitlement decision": ("entitlement decision", "entitlementdecision"),
    "payroll decision": ("payroll decision", "payrolldecision"),
    "why the line exists": ("why the line exists", "why a line exists", "whythelineexists", "whyalineexists"),
    "why a treatment was selected": (
        "why a treatment was selected",
        "why treatment was selected",
        "whyatreatmentwasselected",
    ),
    "allowance decision": ("allowance decision", "allowancedecision"),
    "penalty decision": ("penalty decision", "penaltydecision"),
    "overtime decision": ("overtime decision", "overtimedecision"),
    "shift decision": ("shift decision", "shiftdecision"),
    "public holiday decision": ("public holiday decision", "publicholidaydecision"),
    "break treatment": ("break treatment", "breaktreatment"),
    "missed break": ("missed break", "missedbreak"),
    "minimum engagement": ("minimum engagement", "minimumengagement"),
    "decision evidence": ("decision evidence", "decisionevidence"),
    "Payroll Output": ("payroll output", "payrolloutput"),
    "PayRun Output": ("payrun output", "pay run output", "payrunoutput"),
    "Process Period Output": ("process period output", "processperiodoutput"),
    "Run Output": ("run output", "runoutput"),
    "calculated payroll output": ("calculated payroll output", "calculatedpayrolloutput"),
    "payroll line": ("payroll line", "payrollline"),
    "output line": ("output line", "outputline"),
    "worker output": ("worker output", "workeroutput"),
    "PayRun totals": ("payrun totals", "pay run totals", "payruntotals"),
    "payroll result": ("payroll result", "payrollresult"),
    "finalised outcome truth": ("finalised outcome truth", "finalized outcome truth", "finalisedoutcometruth"),
    "CalcInterpreterRun": ("calcinterpreterrun", "calc interpreter run"),
    "Contact Payroll History": ("contact payroll history", "contactpayrollhistory"),
    "Payroll history": ("payroll history", "payrollhistory"),
    "worker payroll history": ("worker payroll history", "workerpayrollhistory"),
    "contact-level payroll history": (
        "contact level payroll history",
        "contact-level payroll history",
        "contactlevelpayrollhistory",
    ),
    "historical payroll output": ("historical payroll output", "historicalpayrolloutput"),
    "PayRun participation": ("payrun participation", "pay run participation", "payrunparticipation"),
    "worker history": ("worker history", "workerhistory"),
    "payroll outcome history": ("payroll outcome history", "payrolloutcomehistory"),
    "contact deductions": ("contact deductions", "contactdeductions"),
    "contact obligations": ("contact obligations", "contactobligations"),
    "contact tax": ("contact tax", "contacttax"),
    "contact payment": ("contact payment", "contactpayment"),
    "leave history": ("leave history", "leavehistory"),
    "accrual history": ("accrual history", "accrualhistory"),
    "retro history": ("retro history", "retrohistory"),
    "correction history": ("correction history", "correctionhistory"),
    "Gross-to-Net": ("gross to net", "gross-to-net", "grosstonet"),
    "Gross to Net": ("gross to net", "gross-to-net", "grosstonet"),
    "GrossToNet": ("grosstonet", "gross to net", "gross-to-net"),
    "gross earnings": ("gross earnings", "grossearnings"),
    "gross pay": ("gross pay", "grosspay"),
    "net pay": ("net pay", "netpay"),
    "tax withholding": ("tax withholding", "taxwithholding"),
    "withholding": ("withholding",),
    "Process Periods / PayRun Lifecycle": (
        "process periods payrun lifecycle",
        "process periods / payrun lifecycle",
        "process periods and payrun lifecycle",
    ),
    "ProcessPeriod": ("processperiod", "process period"),
    "Process Period": ("processperiod", "process period"),
    "ProcessPeriodGroup": ("processperiodgroup", "process period group"),
    "Process Period Group": ("processperiodgroup", "process period group"),
    "PayRun lifecycle": ("payrunlifecycle", "payrun lifecycle", "pay run lifecycle"),
    "PayRunContact": ("payruncontact", "pay run contact"),
    "RunType": ("runtype", "run type"),
    "RunPurpose": ("runpurpose", "run purpose"),
    "regular PayRun": ("regularpayrun", "regular payrun", "regular pay run"),
    "termination PayRun": ("terminationpayrun", "termination payrun", "termination pay run"),
    "reversal PayRun": ("reversalpayrun", "reversal payrun", "reversal pay run"),
    "adjustment PayRun": ("adjustmentpayrun", "adjustment payrun", "adjustment pay run"),
    "PaymentDate": ("paymentdate", "payment date"),
    "close rolls forward": ("closerollsforward", "close rolls forward"),
    "period close": ("periodclose", "period close"),
    "Contacts / Employee Appointments": (
        "contacts employee appointments",
        "contacts / employee appointments",
        "contacts and employee appointments",
    ),
    "Contact": ("contact",),
    "EmployeeAppointment": ("employeeappointment", "employee appointment"),
    "Employee Appointment": ("employeeappointment", "employee appointment"),
    "Contact history": ("contacthistory", "contact history"),
    "PayRun admission": ("payrunadmission", "payrun admission", "pay run admission"),
    "WorksitePosition": ("worksiteposition", "worksite position"),
    "AwardPositionClass": ("awardpositionclass", "award position class"),
    "classification lens": ("classificationlens", "classification lens"),
    "worker readiness": ("workerreadiness", "worker readiness"),
    "worker attention": ("workerattention", "worker attention"),
    "Award Build": ("award build", "awardbuild"),
    "Award Evidence": ("award evidence", "awardevidence"),
    "AwardEvidenceSet": ("awardevidenceset", "award evidence set"),
    "Durable AwardEvidenceSet": ("durable awardevidenceset", "durable award evidence set"),
    "pay guide evidence": ("pay guide evidence", "payguideevidence"),
    "NEEDS_CONFIGURATION": ("needs_configuration", "needs configuration", "needsconfiguration"),
    "ObjectTime / Source Truth": ("objecttime source truth", "objecttime / source truth"),
    "SourceTruth": ("sourcetruth", "source truth"),
    "Source Truth": ("source truth", "sourcetruth"),
    "raw span hours": ("raw span hours", "rawspanhours"),
    "span hours": ("span hours", "spanhours"),
    "worked hours": ("worked hours", "workedhours"),
    "PayRun inclusion": ("payrun inclusion", "pay run inclusion", "payruninclusion"),
    "current-effective output": ("current effective output", "current-effective output", "currenteffectiveoutput"),
    "dirty contact": ("dirty contact", "dirtycontact"),
    "reprocessing": ("reprocessing",),
    "correction audit": ("correction audit", "correctionaudit"),
    "Imports / Actuals": ("imports actuals", "imports / actuals", "imports and actuals"),
    "Imports and Actuals": ("imports actuals", "imports / actuals", "imports and actuals"),
    "imported actuals": ("importedactuals", "imported actuals"),
    "payroll actuals": ("payrollactuals", "payroll actuals"),
    "actuals lane": ("actualslane", "actuals lane"),
    "imported timesheets": ("importedtimesheets", "imported timesheets"),
    "source-system mapping": ("source system mapping", "source-system mapping", "sourcesystemmapping"),
    "pay code mapping": ("paycodemapping", "pay code mapping"),
    "RateType mapping": ("ratetype mapping", "rate type mapping", "ratetypemapping"),
    "ImportedPositionClassificationMap": (
        "importedpositionclassificationmap",
        "imported position classification map",
    ),
    "ObjectTime source truth": ("objecttime source truth", "object time source truth", "objecttimesourcetruth"),
    "source row": ("sourcerow", "source row"),
    "import provenance": ("importprovenance", "import provenance"),
    "import run": ("importrun", "import run"),
    "unmapped actuals": ("unmappedactuals", "unmapped actuals"),
    "On-costs": ("on costs", "on-costs", "oncosts", "on cost", "on-cost", "oncost"),
    "Employer Liabilities": ("employer liabilities", "employer liability", "employerliabilities", "employerliability"),
    "employer liability": ("employer liability", "employerliability"),
    "superannuation on-cost": (
        "superannuation on cost",
        "superannuation on-cost",
        "superannuation oncost",
        "super on cost",
        "super on-cost",
        "super oncost",
    ),
    "SUPER_ONCOST": ("super_oncost", "super oncost", "super on cost", "superoncost"),
    "PAYROLLTAX_ONCOST": ("payrolltax_oncost", "payrolltax oncost", "payroll tax on cost", "payrolltaxoncost"),
    "WORKCOVER_ONCOST": ("workcover_oncost", "workcover oncost", "workcover on cost", "workcoveroncost"),
    "WorkCover": ("workcover", "work cover"),
    "WIC": ("wic",),
    "RateSource": ("ratesource", "rate source"),
    "date-effective rates": ("date effective rates", "date-effective rates", "dateeffectiverates"),
    "state-scoped RateSource": ("state scoped ratesource", "state-scoped ratesource", "state scoped rate source"),
    "runtime location": ("runtime location", "runtimelocation"),
    "account-wide fallback": ("account wide fallback", "account-wide fallback", "accountwidefallback"),
    "AwardRateType": ("awardratetype", "award rate type"),
    "RateType": ("ratetype", "rate type"),
    "governed basis membership": ("governed basis membership", "governedbasismembership"),
    "Finalisation Readiness": ("finalisation readiness", "finalization readiness", "finalisationreadiness"),
    "finalisation": ("finalisation", "finalization"),
    "finalised outcome": ("finalised outcome", "finalized outcome", "finalisedoutcome"),
    "warning acknowledgement": (
        "warning acknowledgement",
        "warning acknowledgment",
        "warningacknowledgement",
        "warningacknowledgment",
    ),
    "blockers": ("blockers",),
    "warnings": ("warnings",),
    "Payroll Bases readiness": ("payroll bases readiness", "payrollbasesreadiness"),
    "leave readiness": ("leave readiness", "leavereadiness"),
    "missing leave output": ("missingleaveoutput", "missing leave output"),
    "payment readiness": ("payment readiness", "paymentreadiness"),
    "LeaveLedger": ("leaveledger", "leave ledger"),
    "Leave Accrual": ("leaveaccrual", "leave accrual"),
    "Leave Processing": ("leaveprocessing", "leave processing"),
    "LeaveType": ("leavetype", "leave type"),
    "LeaveTypeRule": ("leavetyperule", "leave type rule"),
    "LeaveTypeKind": ("leavetypekind", "leave type kind"),
    "Leave Source Model": ("leavesourcemodel", "leave source model"),
    "Leave Request": ("leave request", "leaverequest"),
    "Leave Requests": ("leave requests", "leaverequests"),
    "LeaveRequest": ("leaverequest", "leave request"),
    "leave workflow": ("leave workflow", "leaveworkflow"),
    "leave submission": ("leave submission", "leavesubmission"),
    "submit leave": ("submit leave", "submitleave"),
    "approve leave": ("approve leave", "approveleave"),
    "reject leave": ("reject leave", "rejectleave"),
    "reopen leave": ("reopen leave", "reopenleave"),
    "leave status": ("leave status", "leavestatus"),
    "IdempotencyKey": ("idempotencykey", "idempotency key"),
    "leave overlap": ("leave overlap", "leaveoverlap"),
    "shortfall substitution": ("shortfall substitution", "shortfallsubstitution"),
    "leave valuation": ("leave valuation", "leavevaluation"),
    "leave posting": ("leave posting", "leaveposting"),
    "leave request payment": ("leave request payment", "leaverequestpayment"),
    "leave balance": ("leave balance", "leavebalance"),
    "leave request preview": ("leave request preview", "leaverequestpreview"),
    "leave source truth": ("leavesourcetruth", "leave source truth"),
    "leave applicability": ("leaveapplicability", "leave applicability"),
    "Contact scope": ("contactscope", "contact scope"),
    "EmployeeAppointment scope": ("employeeappointmentscope", "employee appointment scope"),
    "appointment-aware leave": ("appointment aware leave", "appointment-aware leave", "appointmentawareleave"),
    "final applicability truth": ("finalapplicabilitytruth", "final applicability truth"),
    "leave valuation basis": ("leavevaluationbasis", "leave valuation basis"),
    "accrual basis": ("accrualbasis", "accrual basis"),
    "accrualability": ("accrualability",),
    "CalcInterpreterLine": ("calcinterpreterline", "calc interpreter line"),
    "current-effective payroll output": (
        "current effective payroll output",
        "current-effective payroll output",
        "currenteffectivepayrolloutput",
    ),
    "LeaveProcessRun": ("leaveprocessrun", "leave process run"),
    "TAKEN leave": ("taken leave", "takenleave"),
    "PER_HOUR": ("per hour", "per_hour", "perhour"),
    "Deductions / Obligations": ("deductions obligations", "deductions / obligations", "deductions and obligations"),
    "LibraryDeductionTemplate": ("librarydeductiontemplate", "library deduction template"),
    "AccountDeductionTemplate": ("accountdeductiontemplate", "account deduction template"),
    "ContactPayrollDeduction": ("contactpayrolldeduction", "contact payroll deduction"),
    "PayRunDeductionApplication": ("payrundeductionapplication", "payrun deduction application"),
    "ContactPayrollObligation": ("contactpayrollobligation", "contact payroll obligation"),
    "ContactPayrollObligationLedger": ("contactpayrollobligationledger", "contact payroll obligation ledger"),
    "supplementary deduction memory": ("supplementarydeductionmemory", "supplementary deduction memory"),
    "reducing-balance recovery": ("reducing balance recovery", "reducing-balance recovery", "reducingbalancerecovery"),
    "carry-forward": ("carry forward", "carry-forward", "carryforward"),
    "negative net pay": ("negativenetpay", "negative net pay"),
    "Retro / Replay": ("retro replay", "retro / replay"),
    "retro PayRun": ("retropayrun", "retro payrun", "retro pay run"),
    "supplementary PayRun": ("supplementarypayrun", "supplementary payrun", "supplementary pay run"),
    "attributed period": ("attributedperiod", "attributed period"),
    "paid period": ("paidperiod", "paid period"),
    "finalised outcome memory": ("finalized outcome memory", "finalised outcome memory"),
    "dependency detection": ("dependencydetection", "dependency detection"),
    "bucket rebuild": ("bucketrebuild", "bucket rebuild"),
    "historical bucket evidence": ("historicalbucketevidence", "historical bucket evidence"),
    "correction/replay": ("correction replay", "correction/replay"),
    "Payment Execution / Remittance": (
        "payment execution remittance",
        "payment execution / remittance",
        "payment execution and remittance",
    ),
    "Generate Bank File": ("generatebankfile", "generate bank file"),
    "Bank File": ("bankfile", "bank file"),
    "Period Close": ("periodclose", "period close"),
    "payment allocation": ("paymentallocation", "payment allocation"),
    "payment destination": ("paymentdestination", "payment destination"),
    "bank allocation": ("bankallocation", "bank allocation"),
    "worker net pay": ("workernetpay", "worker net pay"),
    "third-party remittance": ("third party remittance", "third-party remittance", "thirdpartyremittance"),
    "remittance reconciliation": ("remittancereconciliation", "remittance reconciliation"),
    "payment file": ("paymentfile", "payment file"),
    "obligation write-off": ("obligation write off", "obligation write-off", "obligationwriteoff"),
    "Worker Story": ("workerstory", "worker story"),
    "Payroll Bases & Totals": ("payroll bases and totals", "payroll bases totals"),
    "PayrollBucketResult": ("payrollbucketresult", "payroll bucket result"),
    "PayrollBucketDefinition": ("payrollbucketdefinition", "payroll bucket definition"),
    "PayRun Admin Queue": ("payrun admin queue", "admin queue", "payrun queue"),
    "Worker Attention": ("workerattention", "worker attention"),
    "WorkerAttention": ("workerattention", "worker attention"),
    "Worker Attention Centre": ("worker attention centre", "workerattentioncentre", "worker attention center"),
    "Worker Attention / Issue Resolution": (
        "worker attention issue resolution",
        "worker attention / issue resolution",
        "worker attention and issue resolution",
    ),
    "Issue Resolution": ("issue resolution", "issueresolution"),
    "Worker issue": ("worker issue", "workerissue"),
    "WorkerIssue": ("workerissue", "worker issue"),
    "issue scope": ("issue scope", "issuescope"),
    "issue class": ("issue class", "issueclass"),
    "issue severity": ("issue severity", "issueseverity"),
    "deterministic fix link": ("deterministic fix link", "deterministicfixlink"),
    "deterministic fix links": ("deterministic fix links", "deterministicfixlinks"),
    "PayRunContact dirty": ("payruncontact dirty", "pay run contact dirty", "payruncontactdirty"),
    "dirty contacts": ("dirtycontacts", "dirty contacts"),
    "finalisation readiness": ("finalization readiness", "finalisation readiness"),
    "Assurance Snapshot": ("assurancesnapshot", "assurance snapshot"),
    "Command Centre": ("commandcentre", "command centre", "command center"),
    "Movement Review": ("movementreview", "movement review", "payroll movement review"),
    "review-worthy": ("review worthy", "reviewworthy"),
    "comparable period": ("comparableperiod", "comparable period"),
    "rolling average": ("rollingaverage", "rolling average"),
    "trend-only": ("trend only", "trendonly"),
    "Comparison / Remediation": ("comparison remediation", "comparison / remediation"),
    "Award Comparison": ("awardcomparison", "award comparison"),
    "PayRunComparisonRun": ("payruncomparisonrun", "payrun comparison run"),
    "PayRunComparisonLine": ("payruncomparisonline", "payrun comparison line"),
    "PayRunVarianceLine": ("payrunvarianceline", "payrun variance line"),
    "AwardComparisonPolicy": ("awardcomparisonpolicy", "award comparison policy"),
    "comparator award": ("comparatoraward", "comparator award"),
    "imported actuals": ("importedactuals", "imported actuals"),
    "actuals lane": ("actualslane", "actuals lane"),
    "remediation top-up": ("remediation top up", "remediation top-up", "remediationtopup"),
    "variance line": ("varianceline", "variance line"),
    "AwardPositionClassComparisonMap": ("awardpositionclasscomparisonmap", "award position class comparison map"),
    "EmployeeAppointmentAwardClassAssignment": (
        "employeeappointmentawardclassassignment",
        "employee appointment award class assignment",
    ),
    "ObjectTimeClassificationResolution": ("objecttimeclassificationresolution", "object time classification resolution"),
    "Tax / PAYG": ("tax payg", "tax / payg", "payg"),
    "PAYG withholding": ("paygwithholding", "payg withholding"),
    "TaxStory": ("taxstory", "tax story"),
    "taxable basis": ("taxablebasis", "taxable basis"),
    "taxable earnings": ("taxableearnings", "taxable earnings"),
    "worker tax declaration": ("workertaxdeclaration", "worker tax declaration"),
    "withholding instruction": ("withholdinginstruction", "withholding instruction"),
    "ProcessPeriod PaymentDate": ("processperiodpaymentdate", "process period payment date"),
    "payment date": ("paymentdate", "payment date"),
    "gross-to-net": ("gross to net", "gross-to-net", "grosstonet"),
    "finalised totals": ("finalized totals", "finalised totals"),
    "supplementary incremental PAYG": ("supplementary incremental payg", "supplementaryincrementalpayg"),
    "DecisionEvidenceIndex": ("decisionevidenceindex", "decision evidence index"),
    "RateSourceEvidenceIndex": ("ratesourceevidenceindex", "rate source evidence index"),
    "current-effective": ("current effective", "currenteffective"),
    "ObjectTime": ("objecttime", "object time"),
    "PayRun": ("payrun", "pay run"),
    "DeductsOnPublicHoliday": ("deductsonpublicholiday", "deducts on public holiday"),
}


def _split_camel_case(value: str) -> str:
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", value)
    return re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", spaced)


def normalize_for_term_match(value: str) -> str:
    camel_spaced = _split_camel_case(value)
    lower = camel_spaced.lower()
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9]+", " ", lower)).strip()


def term_variants(term: str) -> set[str]:
    variants = {
        normalize_for_term_match(term),
        re.sub(r"[^a-z0-9]+", "", term.lower()),
    }
    for canonical, aliases in PROJECT_TERM_ALIASES.items():
        canonical_variants = {normalize_for_term_match(canonical), re.sub(r"[^a-z0-9]+", "", canonical.lower())}
        alias_variants = {normalize_for_term_match(alias) for alias in aliases} | {
            re.sub(r"[^a-z0-9]+", "", alias.lower()) for alias in aliases
        }
        if variants & (canonical_variants | alias_variants):
            variants |= canonical_variants | alias_variants
    return {variant for variant in variants if variant}


def normalized_text_forms(value: str) -> set[str]:
    normalized = normalize_for_term_match(value)
    compact = re.sub(r"[^a-z0-9]+", "", value.lower())
    return {normalized, compact}


def contains_normalized_term(text: str, term: str) -> bool:
    forms = normalized_text_forms(text)
    return any(variant in form for variant in term_variants(term) for form in forms)


def contains_any_normalized(text: str, terms: list[str] | tuple[str, ...]) -> bool:
    return any(contains_normalized_term(text, term) for term in terms)


def contains_all_normalized(text: str, terms: list[str] | tuple[str, ...]) -> bool:
    return all(contains_normalized_term(text, term) for term in terms)
